version: "3.7"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: backoffice
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  back:
    build:
      context: ./back
      ports:
      - 9000:80
    volumes:
      - .:/var/www/html/

volumes:
  mysql_data: {}